// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJzplRB8YFhnk7peH1CKtzgujdlvncAM',
    appId: '1:1067636088868:web:e3d7fd638c140ffcad78b1',
    messagingSenderId: '1067636088868',
    projectId: 'city-issue-reporter',
    authDomain: 'city-issue-reporter.firebaseapp.com',
    storageBucket: 'city-issue-reporter.firebasestorage.app',
    measurementId: 'G-NSE64J66MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpW4RyF_4jaKwE-tlIqc0_OIIne3X4F08',
    appId: '1:1067636088868:android:83350c6ad6577b2aad78b1',
    messagingSenderId: '1067636088868',
    projectId: 'city-issue-reporter',
    storageBucket: 'city-issue-reporter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-leSxDYCnJzvwleijvjZoHfrnal7glM',
    appId: '1:1067636088868:ios:eb648545af17ed17ad78b1',
    messagingSenderId: '1067636088868',
    projectId: 'city-issue-reporter',
    storageBucket: 'city-issue-reporter.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-leSxDYCnJzvwleijvjZoHfrnal7glM',
    appId: '1:1067636088868:ios:eb648545af17ed17ad78b1',
    messagingSenderId: '1067636088868',
    projectId: 'city-issue-reporter',
    storageBucket: 'city-issue-reporter.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYJzplRB8YFhnk7peH1CKtzgujdlvncAM',
    appId: '1:1067636088868:web:2189830644717778ad78b1',
    messagingSenderId: '1067636088868',
    projectId: 'city-issue-reporter',
    authDomain: 'city-issue-reporter.firebaseapp.com',
    storageBucket: 'city-issue-reporter.firebasestorage.app',
    measurementId: 'G-44JN1LJCJX',
  );
}
